name: Top GitHub Users
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  actions: read
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Top GitHub Users Action
        uses: gayanvoice/top-github-users-action@master
        with:
          token: ${{ secrets.CUSTOM_TOKEN }}
